version: '3.8'

# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  app:
    build:
      target: development  # Use development stage instead of runner
    environment:
      NODE_ENV: development
    volumes:
      - .:/app                    # Mount source code for hot reload
      - /app/node_modules         # Preserve node_modules
      - /app/.next               # Preserve Next.js cache
    command: npm run dev          # Development command
    security_opt: []              # Remove security restrictions for dev
    read_only: false              # Allow writes for development
    tmpfs: []                     # Remove tmpfs restrictions

  postgres:
    ports:
      - "5432:5432"              # Expose PostgreSQL port for local access